# Generated by Django 5.0.1 on 2024-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='timeline',
            field=models.TextField(default='daily'),
            preserve_default=False,
        ),
    ]
