# Generated by Django 5.0.1 on 2024-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0003_posts_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
